<?php $this->flashSession->output();

echo "<h2>Welcome {$userinfo->nickname}</h2>";
$possible_f = array(
  'T' => function () use ($userinfo) { //trades
    echo "<h3>Trades</h3>";
    //print_r($userinfo->trades); //TODO: Write T function
  },

  'I' => function () use ($userinfo) { //inventory
    echo "<h3>Your Inventory</h3>";
    if ($userinfo->inventory->count() > 0) {
      echo "<form method='POST'><table>";
      echo "<thead><tr>
        <th>Qty</th>
        <th>Description<th>
        <th>Action Qty <button type='reset'>Zero</button></th></tr></thead><tbody>";
      foreach ($userinfo->inventory as $inventory_line) {
        echo "<tr>"
          . "<td>{$inventory_line->qty}</td>"
          . "<td>{$inventory_line->items->name}"
          . " &ndash; "
          . "{$inventory_line->items->description}</td>"
          . '<td><input type="number" step="1" min="0" value="0"'
          .  "name='items[{$inventory_line->items->itemid}]'"
          .  " max='{$inventory_line->qty}'/></td>"
          . "</tr>";
      }
      echo "</tbody></table>";
      echo '<button formaction="\Trade\setupProposal" type="submit">Trade</button>&nbsp;'
         . '<button formaction="\Inventory\alchemake" type="submit">Alchemake'
         .'</button></form>';
    }
    else {
      echo "You have no inventory right now. :(";
    }
  },

  'U' => function () use ($userinfo) { //usercard
    ?><!--
    <?php echo "{$userinfo->userid}"; ?>
    -->
    <h3>Usercard</h3>
    <div id="userinfo">
      <ul>
        <li>Basic item delivery: <?= explode($userinfo->last_drop,' ')[0] ?></li>
        <li>AY Allowence: <?= explode($userinfo->last_allowence,' ')[0] ?></li>
        <li>Email Address: <?= $userinfo->emailaddress ?></li>
      </ul>
    </div>
    <?php
  });

foreach (str_split($userinfo->main_order,1) as $section) {
  if (isset($possible_f[$section])) {
    $possible_f[$section]();
  }
}

echo "<pre>";
print_r($userinfo);
echo "</pre>";

?>
