<?php $this->flashSession->output() ?>

<p>Enter a password and email address to login (<a href="/users/save">Create Account?</a>): </p>
<form method="POST" action="/users/loginEmail">
  <label>Email:
    <input type="email" placeholder="you@example.com" name="email" />
  </label>
  <label>Password:
    <input type="password" name="password"/>
  </label>
  <?php
  $nonce = $this->nonce->currentHash();
  ?>
  <input type="hidden" name="time"
    value="<?= $nonce['time'] ?>" />
  <input type="hidden" name="hash"
    value="<?= $nonce['hash'] ?>" />
  <input type="submit" value="Login" />
</form>
