<?php $this->flashSession->output() ?>

<p>Enter a password and email address to login (<a href="/users/save">Create Account?</a>): </p>
<form method="POST" action="/users/loginEmail">
  <label>Email:
    <input type="email" placeholder="you@example.com" name="email" />
  </label>
  <label>Password:
    <input type="password" name="password"/>
  </label>
  <input type="hidden" name="<?= $this->security->getTokenKey() ?>"
    value="<?= $this->security->getToken() ?>" />
  <input type="submit" value="Login" />
</form>
