<p><?php $this->flashSession->output() ?></p>

<p>Enter a password and email address to save your game progress: </p>
<form method="POST" action="new">
  <label>Nickname:
    <input type="text" placeholder="Hello, my name is..." name="nickname"/>
  </label>
  <label>Email:
    <input type="email" placeholder="you@example.com" name="emailaddress" />
  </label>
  <label>Password:
    <input type="password" name="password"/>
  </label>
  <?php
  $nonce = $this->nonce->currentHash();
  ?>
  <input type="hidden" name="time"
    value="<?= $nonce['time'] ?>" />
  <input type="hidden" name="hash"
    value="<?= $nonce['hash'] ?>" />
  <input type="submit" value="Save!" />
</form>
