<h1>How to Alchemake</h1>
<ul>
  <li>Select two or three items in your inventory. Each time you select an item, possible combinations will be highlighted as a hint after just a moment, so don't worry if you don't know them all, or if there's a new one you don't know about yet.</li>
  <li>Click the Alchemake button to confirm your choice. An item will be created from the ones you selected, and placed in your inventory!</li>
  <li>What happens if you select two or three items that don't Alchemake into anything? Try it and see!</li>
  <li>This help message appears when you select less than 2 or more than three items.</li>
</ul>
