<?php
use \Phalcon\Tag;
$this->tag->setDocType(Tag::HTML5);
echo $this->tag->getDocType();
?>


<html>
  <head>
    <link href="/css/alchemake.css" rel="stylesheet" type="text/css" />
    <title>Alchemake</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../js/alchemake.js"></script>
  </head>
  <body>
    <section id="page">
        <h1><a href="/">
                Alchemake
            </a></h1>
      <?php echo $this->getContent() ?>
    </section>
  </body>
</html>